name: convert to firefox

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: set up rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - run: git clone https://github.com/OtsoBear/chrome2moz.git
      
      - name: build chrome2moz
        run: |
          cd chrome2moz
          cargo build --release
      
      - run: |
          git clone https://github.com/NotValra/RoValra.git extension
          cd extension
          rm public/Assets/Contributor.png
          rm public/Assets/icon-16.png
          rm public/Assets/icon-48.png
          rm public/Assets/icon-128.png
          rm public/Assets/RoValraLogo.png
          rm -rf public/Assets/DonatorTiers/

          jq '.name = "RoValra - Firefox Edition" | .description = "An unofficial Firefox version of RoValra (Roblox Improved)"' manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
          npm ci
          npm run build
          cd dist
          zip -r ../../extension.zip .
          cd ../..
          rm -rf extension
      
      - run: ./chrome2moz/target/release/chrome2moz convert -i ./extension.zip -o ./out

      - name: manifest things
        run: |
            jq '.optional_permissions |= map(if . == "contextMenus" then "menus" elif . == "webRequest" then "webRequestBlocking" else . end)' out/manifest.json > out/manifest.json.tmp && mv out/manifest.json.tmp out/manifest.json
            jq '.browser_specific_settings.gecko.update_url = "https://thenamelessdev.github.io/RoValra-firefox/updates.json"' out/manifest.json > out/manifest.json.tmp && mv out/manifest.json.tmp out/manifest.json
      
          
      - name: remove copyrighted files
        run: |
          cd out
          rm public/Assets/Contributor.png
          rm public/Assets/icon-16.png
          rm public/Assets/icon-48.png
          rm public/Assets/icon-128.png
          rm public/Assets/RoValraLogo.png
          rm -rf public/Assets/DonatorTiers/
      - name: clean up
        run: |
            rm -rf chrome2moz
            rm -f extension.zip
            mv out.xpi converted.xpi
            rm -f docs/converted.xpi
            cp converted.xpi docs/

      - name: push to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "no changes"
          else
            git commit -m "convert extension"
            git push
          fi